# Generated by Django 4.2.6 on 2025-08-28 10:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='新闻标题')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('source', models.CharField(max_length=100, verbose_name='新闻来源')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期')),
                ('url', models.URLField(blank=True, null=True, verbose_name='原文链接')),
            ],
            options={
                'verbose_name': '新闻文章',
                'verbose_name_plural': '新闻文章',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='UserMsg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('cardid', models.CharField(max_length=50)),
                ('money', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'UserMsg',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', '存款'), ('withdraw', '取款'), ('transfer_in', '转账收入'), ('transfer_out', '转账支出'), ('payment', '支付'), ('refund', '退款'), ('interest', '利息'), ('other', '其他')], max_length=20)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.CharField(blank=True, max_length=100, null=True)),
                ('counterparty_account', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_no', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='p1.usermsg')),
            ],
            options={
                'db_table': 'Transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='Transaction_user_id_cc9dfb_idx'), models.Index(fields=['transaction_no'], name='Transaction_transac_8acbda_idx')],
            },
        ),
    ]
